apiVersion: v1
kind: Service
metadata:
  name: {{ default "default-http-backend" .Values.defaultBackend.name }}
  labels:
    app: {{ default "default-http-backend" .Values.defaultBackend.name }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    tmp: {{ template "fullname" . }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: {{ default "8080" .Values.defaultBackend.containerPort }}
    protocol: TCP
  selector:
    app: {{ default "default-http-backend" .Values.defaultBackend.name }}
