apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ template "fullname" . }}
  labels:
    k8s-app: "{{ .Chart.Name }}"
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    provider: "devopskube"
spec:
  replicas: 1
  selector:
    k8s-app: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}
        k8s-app: "{{ .Chart.Name }}"
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        provider: "devopskube"
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:{{ .Values.imageTag }}
        name: "{{ .Chart.Name }}"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
          # use downward API
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        # for this to work, the "usual" ssl port of the kube-apiserver needs to reset to
        # another port (444)
        - name: https
          containerPort: 443
          hostPort: 443
        # port 2222 has to be exposed, since we do use it for gogs ssh
        - name: ssh
          containerPort: 2222
          hostPort: 2222
        # we expose 18080 to access nginx stats in url /nginx-status
        # this is optional
        - name: status
          containerPort: 18080
          hostPort: 18080
        args:
        - /nginx-ingress-controller
#        - --watch-namespace=$(POD_NAMESPACE)
        - --default-backend-service=$(POD_NAMESPACE)/{{ default "default-http-backend" .Values.defaultBackend.name }}
        - --nginx-configmap=$(POD_NAMESPACE)/nginx-ingress-conf
# this is a kind of circular dependency to the gogs chart. not really nice.
#        - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-configmap-ssh
