name: keycloak
version: 0.0.2
description: Keycloak Server
keywords:
  - Authentication
home: http://keycloak.org
sources:
  - https://keycloak.org
maintainers:
  - name: Markus M. May
    email: triplem@javafreedom.org
engine: gotpl
